# Generated by Django 3.0.5 on 2020-10-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
